{% set name = "httpx-gssapi" %}
{% set version = "0.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 8c9a4fa526484c1323c0a4436ef1198f34c0f1d6dde0973ea38f960d51e16ef0

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python >=3.9
    - pip
    - setuptools
  run:
    - python >=3.9
    - httpx >=0.16,<0.29
    - python-gssapi

test:
  imports:
    - httpx_gssapi
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/pythongssapi/httpx-gssapi
  summary: A Python GSSAPI authentication handler for HTTPX
  license: ISC
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jack-pappas
    - seowalex
